version: '3.8'

services:
  mesh-node-1:
    build: .
    container_name: mesh-node-1
    environment:
      - NODE_NAME=mesh-node-1
      - STAKE_AMOUNT=5000
    ports:
      - "8080:8080"
      - "8888:8888"
      - "9090:9090"
    volumes:
      - ./data/node1:/app/data
      - ./logs/node1:/app/logs
      - ./models:/app/models:ro
    networks:
      - mesh-network
    restart: unless-stopped

  mesh-node-2:
    build: .
    container_name: mesh-node-2
    environment:
      - NODE_NAME=mesh-node-2
      - STAKE_AMOUNT=3000
    ports:
      - "8081:8080"
      - "8889:8888"
      - "9091:9090"
    volumes:
      - ./data/node2:/app/data
      - ./logs/node2:/app/logs
      - ./models:/app/models:ro
    networks:
      - mesh-network
    restart: unless-stopped
    depends_on:
      - mesh-node-1

  mesh-node-3:
    build: .
    container_name: mesh-node-3
    environment:
      - NODE_NAME=mesh-node-3
      - STAKE_AMOUNT=2000
    ports:
      - "8082:8080"
      - "8890:8888"
      - "9092:9090"
    volumes:
      - ./data/node3:/app/data
      - ./logs/node3:/app/logs
      - ./models:/app/models:ro
    networks:
      - mesh-network
    restart: unless-stopped
    depends_on:
      - mesh-node-1
      - mesh-node-2

  prometheus:
    image: prom/prometheus:latest
    container_name: mesh-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9093:9090"
    networks:
      - mesh-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: mesh-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=mesh123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
      - mesh-network
    restart: unless-stopped
    depends_on:
      - prometheus

networks:
  mesh-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
